apps/academy/urls.py
from django.urls import path

from apps.academy import views

app_name = "academy"

urlpatterns = [
    path("", views.HomeView.as_view(), name="home"),
    path("student/create/", views.StudentInfoView.as_view(), name="student_info"),
    path("student/assignments/", views.AssignmentsView.as_view(), name="assignments"),
]

crud_test/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [path("admin/", admin.site.urls), path("", include("apps.academy.urls"))]

apps/academy/models.py
from django.db import models


class Student(models.Model):
    """A model to manage students info"""

    identifier = models.IntegerField("Identifier")
    name = models.CharField("Name", max_length=100)
    phone = models.IntegerField("Phone")

    class Meta:
        verbose_name = "Student"
        verbose_name_plural = "Students"

    def __str__(self):
        return self.name


class Assignment(models.Model):
    """A model to manage assignments"""

    name = models.CharField("Name", max_length=50)

    class Meta:
        verbose_name = "Assignment"
        verbose_name_plural = "Assignments"

    def __str__(self):
        return self.name


class StudentAssignment(models.Model):
    """A model to manage the students assignments"""

    student = models.ForeignKey(
        Student, verbose_name="Student", on_delete=models.CASCADE
    )
    assignment = models.ForeignKey(
        Assignment, verbose_name="Assignment", on_delete=models.CASCADE
    )

    class Meta:
        verbose_name = "Student Assignments"
        verbose_name_plural = "Students Assignments"

    def __str__(self):
        return f"{self.student.name} - {self.assignment.name}"

apps/academy/forms.py
from django import forms
from django.core.exceptions import ValidationError

from apps.academy import models
from apps.utils import helpers


class StudentForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["identifier"].widget.attrs.update(
            {
                "class": "form-control",
                "style": "background-color: var(--third-color); border-color: black;",
            }
        )
        self.fields["name"].widget.attrs.update(
            {
                "class": "form-control",
                "style": "background-color: var(--third-color); border-color: black;",
            }
        )
        self.fields["phone"].widget.attrs.update(
            {
                "class": "form-control",
                "style": "background-color: var(--third-color); border-color: black;",
            }
        )

    class Meta:
        model = models.Student
        fields = ("identifier", "name", "phone")

    def clean_name(self):
        """Validate if the name does not have numbers"""

        name = self.cleaned_data["name"]
        if helpers.has_numbers(name):
            raise ValidationError("The name cannot contain numbers")

        return name

    def clean_phone(self):
        """Validate if the phone has exactly 10 digits"""

        phone = self.cleaned_data["phone"]
        if len(str(phone)) != 10:
            raise ValidationError("The phone must have 10 digits")

        return phone


class StudentAssignmentForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["student"].widget.attrs.update(
            {
                "class": "form-control",
                "style": "background-color: var(--third-color); border-color: black;",
            }
        )
        self.fields["assignment"].widget.attrs.update(
            {
                "class": "form-control",
                "style": "background-color: var(--third-color); border-color: black;",
            }
        )

    class Meta:
        model = models.StudentAssignment
        fields = ("student", "assignment")

apps/academy/views.py
from django.shortcuts import render, redirect
from django.views.generic import View

from apps.academy import forms


class HomeView(View):
    def get(self, request):
        return render(request, "home.html")


class StudentInfoView(View):
    form_class = forms.StudentForm

    def get(self, request):
        form = self.form_class()
        return render(request, "student_info.html", {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect("academy:home")
        else:
            return render(request, "student_info.html", {"form": form})


class AssignmentsView(View):
    form_class = forms.StudentAssignmentForm

    def get(self, request):
        form = self.form_class()
        return render(request, "assignments.html", {"form": form})

    def post(self, request):
        form = self.form_class(request.POST)
        if form.is_valid():
            form.save()
            return redirect("academy:home")
        else:
            return render(request, "assignments.html", {"form": form})

templates/assignments.html
{% extends "base.html" %}

{% block title %}Assignments{% endblock %}

{% block header %}
    <h1>ASSIGNMENTS</h1>
{% endblock %}

{% block content %}
    <div class="form-container">
        <form action="{% url 'academy:assignments' %}" method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="fieldWrapper">
                {{ form.student.errors }}
                <label for="{{ form.student.id_for_label }}">Student:</label>
                {{ form.student }}
            </div>
            <div class="fieldWrapper">
                {{ form.assignment.errors }}
                <label for="{{ form.assignment.id_for_label }}">Assignment:</label>
                {{ form.assignment }}
            </div>
            <div class="submit-container">
                <input class="btn btn-primary" type="submit" value="Submit">
            </div>
        </form>
    </div>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>{% block title %}NOT IMPLEMENTED TITLE{% endblock %}</title>
</head>
<body>
    {% block header %}NOT IMPLEMENTED HEADER{% endblock %}
    {% block content %}NOT IMPLEMENTED CONTENT{% endblock %}
    <script src="{% static 'index.js' %}"></script>
</body>
</html>

templates/home.html
{% extends "base.html" %}

{% block title %}Home{% endblock %}

{% block header %}
    <h1>HOME</h1>
{% endblock %}

{% block content %}
    <div class="buttons-container">
        <a href="{% url 'academy:student_info'%}"><button type="button" class="btn btn-primary" >Student Info</button></a>
        <a href="{% url 'academy:assignments'%}"><button type="button" class="btn btn-primary">Assignment</button></a>
        <button type="button" class="btn btn-primary" onclick="fetchApi()">API</button>
    </div>
    <div id="fetch-results"></div>
{% endblock %}

templates/student_info.html
{% extends "base.html" %}

{% block title %}Student Info{% endblock %}

{% block header %}
    <h1>STUDENT INFO</h1>
{% endblock %}

{% block content %}
    <div class="form-container">
        <form action="{% url 'academy:student_info' %}" method="POST">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="fieldWrapper">
                {{ form.identifier.errors }}
                <label for="{{ form.identifier.id_for_label }}">Identifier:</label>
                {{ form.identifier }}
            </div>
            <div class="fieldWrapper">
                {{ form.name.errors }}
                <label for="{{ form.name.id_for_label }}">Name:</label>
                {{ form.name }}
            </div>
            <div class="fieldWrapper">
                {{ form.phone.errors }}
                <label for="{{ form.phone.id_for_label }}">Phone:</label>
                {{ form.phone }}
            </div>
            <div class="submit-container">
                <input class="btn btn-primary" type="submit" value="Submit">
            </div>
        </form>
    </div>
{% endblock %}